[package]

name = "cef"
version = "0.0.1"
authors = ["Dylan Ede <dylanede@googlemail.com>"]

[dependencies]

cef-sys = "*"

[dependencies.callc]

git = "https://github.com/dylanede/callc.git"

[target.x86_64-pc-windows-gnu.dependencies]
kernel32-sys = "0.0.5"

[target.x86-pc-windows-gnu.dependencies]
kernel32-sys = "0.0.5"